version: '3'

services:
  
  product_service:
    build: ./application
    container_name: product_service
    environment:
      - IP=0.0.0.0
      - PORT=4200
    ports:
      - '4200:4200'
    expose:
      - '4200'
    networks:
      - hs

  product_nginx:
    build: ./proxy
    container_name: product_nginx
    ports:
      - '4210:4210'
    expose:
      - '4210'
    networks:
      - hs

networks:
  hs:
    external: true